sudo: required

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
    - INSTANCE=default-centos-5
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-fedora-20
    - INSTANCE=default-fedora-21
    - INSTANCE=default-fedora-22
    - INSTANCE=default-fedora-23
    - INSTANCE=remi-php55-centos-5
    - INSTANCE=remi-php55-centos-6
    - INSTANCE=remi-php55-centos-7
    - INSTANCE=remi-php56-centos-5
    - INSTANCE=remi-php56-centos-6
    - INSTANCE=remi-php56-centos-7
    - INSTANCE=remi-php56-fedora-20
    - INSTANCE=remi-php70-test-centos-6
    - INSTANCE=remi-php70-test-centos-7
    - INSTANCE=remi-php70-test-fedora-21
    - INSTANCE=remi-php70-test-fedora-22
    - INSTANCE=remi-php70-test-fedora-23
    - INSTANCE=remi-php70-centos-6
    - INSTANCE=remi-php70-centos-7
    - INSTANCE=remi-php70-fedora-21
    - INSTANCE=remi-php70-fedora-22
    - INSTANCE=remi-php70-fedora-23
    - INSTANCE=remi-safe-centos-6
    - INSTANCE=remi-safe-centos-7
    - INSTANCE=remi-test-centos-5
    - INSTANCE=remi-test-centos-6
    - INSTANCE=remi-test-centos-7
    - INSTANCE=remi-test-fedora-20
    - INSTANCE=remi-test-fedora-21
    - INSTANCE=remi-test-fedora-22
    - INSTANCE=remi-test-fedora-23
    - INSTANCE=remi-centos-5
    - INSTANCE=remi-centos-6
    - INSTANCE=remi-centos-7
    - INSTANCE=remi-fedora-20
    - INSTANCE=remi-fedora-21
    - INSTANCE=remi-fedora-22
    - INSTANCE=remi-fedora-23

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_YAML=.kitchen.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
