sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

services: docker

env:
  matrix:
  - INSTANCE=remi-centos-5
  - INSTANCE=remi-centos-6
  - INSTANCE=remi-centos-7
  - INSTANCE=remi-fedora-23
  - INSTANCE=remi-php55-centos-5
  - INSTANCE=remi-php55-centos-6
  - INSTANCE=remi-php55-centos-7
  - INSTANCE=remi-php56-centos-5
  - INSTANCE=remi-php56-centos-6
  - INSTANCE=remi-php56-centos-7
  - INSTANCE=remi-php70-centos-6
  - INSTANCE=remi-php70-centos-7

# Don't `bundle install`
install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
